name: Stock Alert

on:
  schedule:
    - cron: "30 13 * * 1-5"  # Runs at 6:30 AM PT (13:30 UTC) on weekdays
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install yfinance ta requests

    - name: Run stock alert script
      run: python main.py
